shared:
  my_ci: &common_checks
    - check-success="Code checks"
    - check-success="Scalops tests (11, 3.2.1, ubuntu-latest)"
    - check-success="Scalops tests (17, 3.2.1, ubuntu-latest)"
    - check-success="Scalops integration tests (11, 3.2.1, ubuntu-latest)"
    - check-success="Scalops integration tests (17, 3.2.1, ubuntu-latest)"

queue_rules:
  - name: default
    conditions: *common_checks

pull_request_rules:
  - name: automatic merge for scala-steward PRs
    conditions:
      - author=4ndrz3j-r35531[bot]
    actions:
      queue:
        name: default
  - name: automatic merge for main when CI passes
    conditions:
      - base=main
      - label=ready-to-merge
      - and: *common_checks
    actions:
      queue:
        name: default
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: