addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "2.1.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "2.0.6")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.11")
