name: Scalops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Scalops tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
        scala: ["3.2.1", "3.2.2-RC2"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Run tests
      timeout-minutes: 5
      run: sbt scalops/Test/test

  int:
    name: "Scalops integration tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
        scala: ["3.2.1", "3.2.2-RC2"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Run integration tests
      timeout-minutes: 10
      run: sbt scalops/IntegrationTest/test
